# https://levelup.gitconnected.com/dockerized-crud-restful-api-with-go-gorm-jwt-postgresql-mysql-and-testing-61d731430bd8

version: "3.8"

services:
  server:
    build: .
    env_file:
      - .env

  database:
    image: postgres:13-alpine
    container_name: postgres_database
    ports:
#      todo: use DB_PORT
      - '5431:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
#    volumes:
#      - database_postgres:/var/lib/postgresql/data
#    networks:
#      - net

  redis:
    image: redis:6.0-alpine3.12

networks:
  net:
    driver: bridge
