version: "3.8"

services:
  server:
    build: .
    env_file:
      - .env
    ports:
      - '${SERVER_PORT_OUTER}:${SERVER_PORT_INNER}'
    volumes:
      - media_root:/app/media_root/
    depends_on:
      - database
      - redis

  nginx:
    image: nginx:1.19-alpine
    env_file:
      - .env
    ports:
      - '${APP_PORT_OUTER}:80'
    volumes:
      - media_root:/usr/share/nginx/media:ro
      - ./nginx/:/etc/nginx/conf.d:ro
    depends_on:
      - server

  web_client:
    build: web_client
    env_file:
      - .env
    ports:
      - '${WEB_CLIENT_PORT_OUTER}:80'

  database:
    image: postgres:13-alpine
    container_name: postgres_database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
#    volumes:
#      - database_postgres:/var/lib/postgresql/data
#    networks:
#      - net

  redis:
    image: redis:6.0-alpine3.12


volumes:
  media_root:
    name: 'media_root_001'

networks:
  net:
    driver: bridge

# https://levelup.gitconnected.com/dockerized-crud-restful-api-with-go-gorm-jwt-postgresql-mysql-and-testing-61d731430bd8
